### ISSUE TITLE
Epidemic alert grid

### ISSUE THREAD

**Issue by AnjanaSenanayake** [AnjanaSenanayake/Arogya-Health-Service-Platform#4]
We implemented a feature in the app to keep track of users with communicable diseases.

**Below background info**
[_functionality is to track nearby people in-order to track disease spread. When the functionality is on, nearby devices will communicate with each other and keep track of them using the hash of each user registered to the system. This track will keep 2 weeks of such records internally. By any chance, if a person is diagnosed with a communicable disease(epidemics or pandemic level), authorities can broadcast a warning for all the devices which have been contacted(via nearby message API) with the patient's device within the past 2 weeks with the contacted location and the possible disease threat_.]

**Tasks**

- [ ] Implement a grid to show the epidemic alerts submitted by users. 

- [ ] When a user submits an alert to the system it should show there. Then the responsible official has to verify and confirm the alert with a button click or in a similar manner. 
- [ ] Then the system will broadcast a warning alert to all the devices which have been in contact(in contact means even sitting beside him/her in the daily commute) with the infected person. (**For this part code is implemented has to execute that on button click**)
